дз 1
anykuzya/hh-hw pull request #1
Opened 2020-11-26 07:29 UTC by anykuzya

Я еще не успела пройтись по всем ссылкам из конца презентации, поэтому что-то может быть неидеально :)
Но вроде всё работает!

2020-11-26 07:33 UTC, anykuzya commented on src/hw/streamapi/common/Person.java
> +    private String secondName; // может всё-таки last name?) а то middle какой-то полуторный, что ли?)
Это вопрос, который до сих пор меня мучает! Особенно когда вызывается конструктор с отчеством, который должен вызываться как `new Person(0, "Анна", "Кузнецова", "Алексеевна" /*instant*/)`
И что конструтора который сам бы добавлял Instant.now() нет, тоже нежножко удивило

2020-11-26 07:36 UTC, anykuzya commented on src/hw/streamapi/tasks/Task8.java
> +    // TODO: упомянуть в пулл-реквесте: откуда взялась фальшивая персона -- это, конечно, загадка, но ШТО Ж
откуда фальшивая персона? я ее создала и использовала в тестах, но где гарантия, что этот метод будет вызываться только на списках, в которых мы должны дропнуть первый элемент?

2020-11-26 07:37 UTC, anykuzya commented on src/hw/streamapi/tasks/Task8.java
> +    public List<String> getFirstNamesWithoutFake(List<Person> persons) {
поменяла нейминг, чтобы можно было задаться вопросом выше при его использовании + уточнила, что здесь имя -- это только имя

2020-11-26 07:39 UTC, anykuzya commented on src/hw/streamapi/tasks/Task8.java
> +    // получаем сет уникальных пользовательских имен
в целом непонятно, зачем писать комментарии, если можно делать понятный нейминг, идея ж всё закомплитит

2020-11-26 07:39 UTC, anykuzya commented on src/hw/streamapi/tasks/Task8.java
> +        return new HashSet<>(getFirstNamesWithoutFake(persons));
ну и стримы здесь вообще никчему, тем более зачем делать distinct перед сбором в сет

2020-11-26 07:40 UTC, anykuzya commented on src/hw/streamapi/tasks/Task8.java
> +    // Для фронтов выдадим полное имя, а то сами не могут
за что так с фронтами, они стараются, кнопки перекрашивают

2020-11-26 07:41 UTC, anykuzya commented on src/hw/streamapi/tasks/Task8.java
> +        return Stream.of(person.getFirstName(), person.getMiddleName(), person.getSecondName())
в изначальной реализации было second + first + second, но мы явно хотим тут задействовать отчество

2020-11-26 07:45 UTC, anykuzya commented on src/hw/streamapi/tasks/Task8.java
> +    public Map<Integer, String> getPersonIdsToFullNamesMapping(Collection<Person> persons) {
И снова: в целом непонятно, зачем писать комментарии, если можно делать понятный нейминг

2020-11-26 07:45 UTC, anykuzya commented on src/hw/streamapi/tasks/Task8.java
> +        people.retainAll(persons2);
я не придумала, как сделать это на стримах. можно было бы еще здесь использовать removeAll и удалять из первого сета элементы второго сета -- и возвращать из метода результат removeAll (то есть если хоть один элемент удалился, значит, пересечение было), но кажется, что такой код как есть понять проще

2020-11-26 07:47 UTC, anykuzya commented on src/hw/streamapi/tasks/Task8.java
> +        return numbers.filter(n -> n % 2 == 0).mapToInt(Integer::intValue).count();
что этот метод вообще здесь делает? я бы его просто удалила, но пусть это будет после уточнения, что он тут не нужен

2020-11-26 07:47 UTC, anykuzya commented on src/hw/streamapi/tasks/Task8.java
> +        Boolean codeSmellsGood = null;
код -- это деньги, а деньги не пахнут *just joke*

2020-11-26 16:50 UTC, genroelgvozo requested changes

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/common/Person.java
> +    private String secondName; // может всё-таки last name?) а то middle какой-то полуторный, что ли?)
Ну с secondName наверное ты права
А вот с конструктором - ну тут все делается по нужде. Если видно что везде сетится Instant.now то можно и сделать, здесь была не в этом задача, я даже не задумывался)

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task1.java
>      private List<Person> findOrderedPersons(List<Integer> personIds) {
Вопросов не имею)

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task2.java
> +    // но мне кажется, что так читаемее, а стримы из половинок мы и во флэтмапе создаем, если я всё правильно понимаю
Да, все верно, разумеется сортировка n log n, и быстрее сравнением нельзя.
Про конкат - читаемо, я тоже бы так написал, но и с флатмап тоже норм. Первый вариант не очень, как минимум много строк, расширение массива и т.д.

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task3.java
> +    // какой класс компаратор классный и что есть не просто comparing, а ещё и thenComparing
Действительно для того чтобы это узнать)
Вопросов не имею

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task4.java
> +    //            .collect(toList());
Норм в одной, если мало операций (и строка влезает в длину по стайлгайду)

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task5.java
> +            .map(person -> convert(person, personAreaIds.get(person.getId())))
Да, тут все гуд

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task6.java
> +    private static Stream<String> getPersonAreas(Integer userId, Set<Integer> userAreas,
Чисто по стилю - лучше если сюда передать сразу персону, потому что странная такая функция, принимает кучу мап, сет, и айдишку персоны). Можно вместо двух параметров как минимум один

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task6.java
> +        return personAreaIds.entrySet().stream() // это стрим с айдишниками юзеров
и тут от одной мапы избавиться можно, если бежать сразу по persons (причем идеологически это более правильно, потому что у персоны может не быть ареек, и тут вопрос, а будет ли она во второй мапе или нет?  А может вообще в мапу всех передали, а в коллекции только нужные, тогда твой код еще и упадет)
И после того как бежишь, там уже берешь флатмап из второй мапы по айди

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task6.java
> +        return personAreaIds.entrySet().stream() // это стрим с айдишниками юзеров
Но в целом норм решение

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task7.java
> +    // но по производительности это вроде не влияет, а вот читать что происходит в отдельных преобразованиях, проще
Тут кстати не соглашусь, сам бы написал .flatMap(company -> company.getVacancies().stream()), но это на вкус, задача ок)

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task8.java
> +    // TODO: упомянуть в пулл-реквесте: откуда взялась фальшивая персона -- это, конечно, загадка, но ШТО Ж
ну мало ли что бывает, легаси всякое. Допустим у вас может быть всегда персона-черновик, куда сохраняются данные с формы, пока персону еще не создали. Но вот забыли вы статус ввести, и она у вас в селекты попадает (всякое в продакшене бывает). Короче объяснить можно, понять нельзя, но делать что-то нужно)

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task8.java
> +    public List<String> getFirstNamesWithoutFake(List<Person> persons) {
Все ок, только вопрос, чем принципиально скип лучше чем ремув? кроме того что со стримами и скип выглядит короче

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task8.java
> +    // получаем сет уникальных пользовательских имен
В целом комментарии для вас, а так естественно комментарии в боевом коде почти не пишем)

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task8.java
> +        return new HashSet<>(getFirstNamesWithoutFake(persons));
Верно

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task8.java
> +    // Для фронтов выдадим полное имя, а то сами не могут
Да я фулстак (именно через а, а не через э), это самоирония))

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task8.java
> +            .flatMap(Optional::stream)
ой... а можно вместо этого всего один фильтр?)

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task8.java
> +    public Map<Integer, String> getPersonIdsToFullNamesMapping(Collection<Person> persons) {
тут все ок

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task8.java
> +        people.retainAll(persons2);
Вопрос - за сколько будет работать retainAll и отчего это будет зависить?
Поэтому намек
1) если стримы - то anyMatch
2) если не стримы - то класс Collections
Вообщем, поищем давай решение побыстрее и красивее))

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task8.java
> +        return numbers.filter(n -> n % 2 == 0).mapToInt(Integer::intValue).count();
да тут вроде все не нужно, жизнь тлен
Но хотелось бы услышать почему нельзя делать так, как было изначально))

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task8.java
> +        return numbers.filter(n -> n % 2 == 0).mapToInt(Integer::intValue).count();
И зачем кстати делать mapToInt? каунт и так норм отработает, зачем делать лишний анбоксинг?

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task8.java
> +        boolean reviewerDrunk = true;
Ну хоть кто-то написал правду

2020-11-26 16:50 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task8.java
> +        Boolean codeSmellsGood = null;
Изначальный код деньгами не пахнул (ba-dum-tss)

2020-11-27 11:03 UTC, anykuzya commented on src/hw/streamapi/tasks/Task8.java
> +    public List<String> getFirstNamesWithoutFake(List<Person> persons) {
тем, что ремув первого элемента из списка работает за линию, а со стримом при пропуске первого элемента остальные элемента стрима не перекладываются на предыдущее место?

2020-11-27 11:21 UTC, anykuzya commented on src/hw/streamapi/tasks/Task8.java
> +        return numbers.filter(n -> n % 2 == 0).mapToInt(Integer::intValue).count();
mapToInt, вылез когда мне показалось, что мы хотим считать нечетные *facepalm* (я тогда хотела мапнуть число в его остаток от двойки и просуммировать вместо фильтра и каунта)
конечно, он тут не нужен

так как было изначально делать не хорошо потому что это штука, которая вообще-то от состояния классна не зависит (и вообще можно сделать это метод статическим), но здесь было использование поля класса (которое к тому же очень далеко от своего использования объявлено), и это хочется упростить

2020-11-27 11:31 UTC, anykuzya commented on src/hw/streamapi/tasks/Task8.java
> +            .flatMap(Optional::stream)
ох, разумеется :facepalm:

2020-11-27 11:37 UTC, anykuzya commented on src/hw/streamapi/tasks/Task8.java
> +        people.retainAll(persons2);
retainAll, похоже, будет работать за линию от размера второй коллекции, так что даже если мы хотим его использовать, надо выбирать ту коллекцию, которая больше, чтобы создавать people; c ремувом будет то же самое
можно вообще написать супер-оптимально, чтобы при каком-то соотношении размеров использовался способ с retainAll/removeAll меньшей коллекции из большей, а если их размеры сравнимы, то делать через стримы или коллекции (пока думаю, как именно)

2020-11-27 11:55 UTC, anykuzya commented on src/hw/streamapi/tasks/Task6.java
> +        return personAreaIds.entrySet().stream() // это стрим с айдишниками юзеров
щас как раз не падает, потому что если у персоны нет ареек, то когда я бегу по personAreaIds я на такую пресону на натыкаюсь
либо я неправильно поняла проблему, которую ты описываешь

но я сейчас попробую еще упростить

2020-11-27 12:34 UTC, anykuzya commented on src/hw/streamapi/tasks/Task6.java
> +    private static Stream<String> getPersonAreas(Integer userId, Set<Integer> userAreas,
поправила

2020-11-27 12:37 UTC, anykuzya commented on src/hw/streamapi/tasks/Task6.java
> +        return personAreaIds.entrySet().stream() // это стрим с айдишниками юзеров
и тут вроде поправила, но в цело не сильно поменялось. но в мапу хожу через getOrDefault, так что теперь не упадет с персоной, у которой не ареек (в check тоже добавила)

2020-11-29 17:10 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task8.java
> +    public List<String> getFirstNamesWithoutFake(List<Person> persons) {
И это тоже, правда суммарно асиптотически все равно за линию работает.
Главный принципиальный момент (не про скорость), в том что не рекомендуется изменять входные параметры, этого могут не ожидать пользователи вашей функции

2020-11-29 17:16 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task8.java
> +        people.retainAll(persons2);
На самом деле дело не только в размере) дело все в том, сколько работает contains (он юзается внутри retainAll) и у HashSet это О(1) а не хэшсета O(n)
таким образом метод с retain если persons1 не является Хэшсетом (ты сделала хеш сет, но вроде не с той стороны, хотя я может уже запутался))
А дисджойнт пытается найти хешсет среди двух коллекций, если таковой есть
Вообще гарантированно за O(n) суммарно будет работать такой код
return persons1.stream().anyMatch(new HashSet<>(persons2)::contains);
с retainAll тоже норм, только надо точно проверить какую из коллекций обернуть в хешсет, ну и строк по любому больше)

2020-11-29 17:17 UTC, genroelgvozo commented on src/hw/streamapi/tasks/Task8.java
> +        return numbers.filter(n -> n % 2 == 0).mapToInt(Integer::intValue).count();
Переменную пришлось вынести в класс, потому что локальную в методе нельзя использовать в лямбда функции (она не эффективно финал - есть такой термин в джаве). Но дело основное было в многоточности, что если стрим параллельный, то изначальный код выдавал неправильный результат, а вот count работает всегда правильно

2020-11-29 17:18 UTC, genroelgvozo approved these changes

2020-11-30 07:26 UTC, anykuzya commented on src/hw/streamapi/tasks/Task8.java
> +    public List<String> getFirstNamesWithoutFake(List<Person> persons) {
а, логично, спасибо!

2020-11-30 07:29 UTC, anykuzya commented on src/hw/streamapi/tasks/Task8.java
> +        return numbers.filter(n -> n % 2 == 0).mapToInt(Integer::intValue).count();
А, окей, спасибо

2020-11-30 07:29 UTC, merged