домашка по sql
anykuzya/hh-hw pull request #2
Opened 2020-12-09 22:31 UTC by anykuzya

Здесь пока нет последнего запроса, потому что я пока не сообразила, как его написать.
Но открою pr так, чтобы было время поправить замечания по другим запросам, если они возникнут.

2020-12-10 12:15 UTC, anykuzya commented on sql-hw/queries.sql
> +-- имя работодателя для первых 10 вакансий, у которых не указана зарплата,
уже заметила, что здесь я потеряла условие "у которых не указана зп", поправлю

2020-12-10 14:55 UTC, anykuzya commented on sql-hw/queries.sql
> +-- Вывести минимальное и максимальное время от создания вакансии до первого отклика для каждого города.
пока в этом запросе есть ошибка: тут не до первого отклика, а до любого :( думаю, как это пофиксить

2020-12-20 18:49 UTC, eldmitrieva requested changes

2020-12-20 18:49 UTC, eldmitrieva commented on sql-hw/defining-schema.sql
> +);
стоит добавить пустую строку в конце файла

2020-12-20 18:49 UTC, eldmitrieva commented on sql-hw/defining-schema.sql
> +CREATE TYPE conversation_type AS ENUM ('отклик', 'приглашение'); -- когда кандидат апплаится на вакансию, это отклик
типы лучше писать по-английски, чтобы избежать возможных проблем с кодировкой. Ну и это тип данных, логично, что если остальные типы мы пишем по-английски, то и тут тоже стоит писать по-английски

2020-12-20 18:49 UTC, eldmitrieva commented on sql-hw/queries.sql
> +    GROUP BY company_name
У тебя нет ограничения на уникальность имени работодателя (это и не нужно, могут быть работодатели с одинаковым названием), а тут ты таких одинаковых работодателей схлопываешь в одного

2020-12-20 18:49 UTC, eldmitrieva commented on sql-hw/queries.sql
> +) SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY vacancies_amount) FROM vacancies_per_employer;
SELECT и FROM лучше перенести на новые строки

2020-12-20 18:49 UTC, eldmitrieva commented on sql-hw/queries.sql
> +    FROM conversation
у тебя в conversation хранятся и отклики, и приглашения, а по заданию надо посчитать только количество откликов

2020-12-20 18:49 UTC, eldmitrieva commented on sql-hw/queries.sql
> +    SELECT count(v.vacancy_id) AS conversation_amount, employer_id
лучше считать не v.vacancy_id, а conversation_id

2020-12-20 18:49 UTC, eldmitrieva commented on sql-hw/queries.sql
> +    FROM conversation
тут бы добавить алиас для таблицы, раз у вакансий есть алиас, чтобы одинаково было

2020-12-20 18:49 UTC, eldmitrieva commented on sql-hw/queries.sql
> +    (SELECT DISTINCT company_name, conversation_amount
этим DISTINCT ты убираешь компании, у которых одинаковые названия

2020-12-20 18:49 UTC, eldmitrieva commented on sql-hw/queries.sql
> +    (SELECT DISTINCT company_name, conversation_amount
Точно ли здесь нужен вложенный селект?

2020-12-20 18:49 UTC, eldmitrieva commented on sql-hw/queries.sql
> +SELECT area_name, max(time_to_first_conversation), min(time_to_first_conversation)
тут столбцов уже многовато, лучше каждый на новой строке писать, так будет более читаемо

2020-12-20 18:49 UTC, eldmitrieva commented on sql-hw/queries.sql
> +FROM (SELECT area_name, min(c.contacted_at - v.opened_at) AS time_to_first_conversation, v.vacancy_id
тут тожн лучше на новые строки переносить

2020-12-20 18:49 UTC, eldmitrieva commented on sql-hw/queries.sql
> +    LIMIT 5) AS top_5_companies_most_interest_vacancies_conversation_amount;
Тут тоже просится перенос строки

2020-12-20 18:49 UTC, eldmitrieva commented on sql-hw/queries.sql
> +    GROUP BY v.vacancy_id, area_name
тут ты схлопываешь города с одинаковыми названиями в один

2020-12-20 18:49 UTC, eldmitrieva commented on sql-hw/queries.sql
> +FROM (SELECT area_name, min(c.contacted_at - v.opened_at) AS time_to_first_conversation, v.vacancy_id
Если перенести вложенный запрос в WITH, то будет выглядеть аккуратнее

2020-12-21 14:16 UTC, anykuzya commented on sql-hw/queries.sql
> +    GROUP BY company_name
ага! и join здесь нужен не inner, a full или right, с inner не учитываются компании с 0 вакансий

2020-12-21 15:20 UTC, anykuzya commented on sql-hw/queries.sql
> +    (SELECT DISTINCT company_name, conversation_amount
ага, но без него у меня может попасть в выборку одна и та же компания, у которой есть две вакансии, у которых на порядок больше откликов, надо значит что-то в with поменять, подумаю

2020-12-21 15:20 UTC, anykuzya commented on sql-hw/queries.sql
> +    (SELECT DISTINCT company_name, conversation_amount
не точно)

2020-12-22 09:24 UTC, anykuzya commented on sql-hw/filling-database.sql
> +INSERT INTO vacancy (employer_id, position_name, opened_at, compensation_from, compensation_to, compensation_gross, area_id, other)
вопрос: есть ли способ наложить такое ограничение на колонку area_id, чтобы нельзя было добавить в таблицу вакансию с городом, в котором нет работодателя (т.е. например JetBrains есть в москве и питере, и это можно узнать по таблице employer_to_area, и как запретить класть в эту таблицу вакансию от джетбрейнс вакансию, например, с area_id = 4 (у меня это воронеж))?

2020-12-22 09:25 UTC, anykuzya commented on sql-hw/filling-database.sql
> +INSERT INTO vacancy (employer_id, position_name, opened_at, compensation_from, compensation_to, compensation_gross, area_id, other)
ой, я даже писала этот вопрос в комментах в коде к созданию таблицы и забыла про него :facepalm:

2020-12-22 09:30 UTC, anykuzya commented on sql-hw/queries.sql
> +-- Вывести минимальное и максимальное время от создания вакансии до первого отклика для каждого города.
тут я тоже т.к. делаю inner join теряю те города, в которых не было вакансий (или откликов на них), но не очень понятно по заданию, какое поведение ожидается от запроса: выводить эти города со значением null в min и max, ли выкинуть их из выборки, как у меня получилось

2020-12-22 09:42 UTC, anykuzya commented on sql-hw/queries.sql
> +    WHERE type = 'response' -- это если мы хотим ограничить таким условием не рассматривать случаи, когда кандидата
хотя вот тут, наверное, и есть ответ на вопрос выше: как бы я не джойнила, с этим фильтром все равно останутся только города/вакансии с откликами, у всего остального будет type null и оно отфильтруется этим условием

2020-12-22 09:52 UTC, anykuzya commented on sql-hw/queries.sql
> +    (SELECT DISTINCT company_name, conversation_amount
вроде переделала без него)
мне почему-то казалось, что мы не можем такую логику как case запихнуть в order by, поэтому я пыталась ее в отдельный столбец во вложенном селекте вытащить, но этот ларчик проще открывался

2020-12-22 09:55 UTC, anykuzya commented on sql-hw/queries.sql
> +    (SELECT DISTINCT company_name, conversation_amount
переписала запрос

2020-12-22 10:45 UTC, eldmitrieva approved these changes

2020-12-22 10:45 UTC, eldmitrieva commented on sql-hw/filling-database.sql
> +INSERT INTO vacancy (employer_id, position_name, opened_at, compensation_from, compensation_to, compensation_gross, area_id, other)
да, теоретически можно через constraint, но нежелательно все ограничения делать через базу, в таком случае сложнее становится поддержка кода. А конкретно в нашем случае такое ограничение и не нужно, потому что это может быть вакансия для удаленной работы, тогда она может быть опубликована в любом городе, или им нужен временный сотрудник в Воронеже, например, провести опрос по использованию их продукта компаниями из Воронежа

2020-12-22 14:25 UTC, merged